### ISSUE TITLE
Browsing issues

### ISSUE THREAD

**Issue by Matlemad** [videoDAC/android#61]
First of all, congrats on this amazing job!!

- As a **user** watching a publisher livestream, I want to be able to **browse** back to the list of publishers without the app closing, so I can switch publisher and check out other content.
This can be achieved with a **navigation button**, or as @chrishobcroft suggested, simply by **tapping** the screen.

- As a **user** watching a livestream, I want to able to **copy the "Top-up" address** without closing the app, so I can finish watching something if I'm interested.
This could be achieved by a simple <copy> icon next to the residual credit.

**Comment by chrishobcroft** [comment]
Thank you for this, @Matlemad

Your first point I think is now fixed in the latest release of the Consumer app, per this PR: https://github.com/videoDAC/android/pull/69

For the second point, I have included this in a broader discussion about UI changes, per this issue: https://github.com/videoDAC/android/issues/70

Please let me know if you are OK with this being discussed over there, and if so, whether we can close this issue.

**Comment by Matlemad** [comment]
we can close it!

**Comment by chrishobcroft** [comment]
Thank you, @Matlemad
